[package]
name = "ffs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fuse = "0.3"
time = "0.1"
libc = "0.2"
log = "0.3"
env_logger = "0.3"
